[package]
name = "muxide"
version = "0.1.0"
authors = ["aidos9 <20310468+aidos9@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vte = "0.9"
nix = "0.19"
libc = "0.2"
chan-signal = "0.3"
termion = "1.5"
num-traits = "0.2"