[environment]
panel_init_command = "/usr/local/bin/fish"
selected_workspace_color = "default"
selected_panel_color = "default"
show_workspaces = true
prompt_text = ">"

[borders]
vertical_character = "|"
horizontal_character = "-"
intersection_character = "+"
color = "default"

[[keys]]
key = "c"
command = "OpenPanel"
args = ["a"]