[environment]
panel_init_command = "/usr/local/bin/fish"
default_border_color = "default"

[command_prompt]
prompt_text = ">"
enabled = true

[top_border]
color = "default"
enabled = true

[[keys]]
key = "c"
command = "OpenPanel"
args = ["a"]